development:
  adapter: postgresql
  encoding: utf8
  database: flash_card_quiz_development
  username: amaes
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: flash_card_quiz_test
  username: amaes
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: flash_card_quiz_production
  username: amaes
  password: 
